name: MedNet-PVS
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit   

  - pip

  - pip:
    - batchgenerators>=0.23
    - dicom2nifti
    - einops
    - matplotlib
    - medpy
    - ml_collections
    - nibabel
    - nnunetv2 
    - numpy
    - pandas
    - pillow
    - requests
    - scikit-image>=0.14
    - scikit-learn
    - scipy
    - SimpleITK
    - surface-distance
    - timm
    - tifffile
    - tqdm
